HotZone/HotZone_config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('orders/', include('orders.urls')),
    path('recordPage/', include('recordPage.urls')),
]

HotZone/orders/urls.py
from django.urls import path
from orders import views

urlpatterns = [
    path('customerOrders/<int:customer>',
         views.CustomerViewOrders.as_view(),
         name='customer-orders'),
    path('customers',
         views.CustomersViewAll.as_view(),
         name='customers'),
]

HotZone/orders/models.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    def __str__(self):
        return self.name

class Order(models.Model):
    time = models.DateTimeField()
    status = models.CharField(max_length=10)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item)
    def __str__(self):
        return self.name

HotZone/templates/case.html
<style>
    table,
    th,
    td {
        border: 1px solid rgb(235, 59, 59);
        border-collapse: collapse;
    }

    table {
        margin: 20px 0;
    }

    .highlight {
        background-color: #fa9da9;
    }

    input {
        width: 100%;
    }
</style>

<h1>Showing all location by {{ case.caseNumber }}</h1>

<div style="display: flex; flex-direction: column">
    <a href="{% url 'case-delete' case.pk %}">Delete Case</a>
    <a href="{% url 'case-update' case.caseNumber %}">Update Case</a>
</div>

<form>
    <table style="width:100% ">
        <tr>
            <th>Case Number</th>
            <th>Date Confirmed</th>
            <th>Local or Imported</th>
            <th>Patient Name</th>
            <th>ID Number</th>
            <th>Date of Birth</th>
            <th>Virus Name</th>
            <th>Disease</th>
            <th>Max Infectious Period</th>
        </tr>
        <tr>
            <td>{{ case.caseNumber }}</td>
            <td>{{ case.dateConfirmed }}</td>
            <td>{{ case.localOrImported }}</td>
            <td>{{ case.patientName }}</td>
            <td>{{ case.idNumber }}</td>
            <td>{{ case.dateOfBirth }}</td>
            <td>{{ case.virusName }}</td>
            <td>{{ case.disease }}</td>
            <td>{{ case.maxInfectiousPeriod }}</td>
        </tr>
    </table>
    <!-- <input type="submit" value="Modify Case"> -->
</form>

<table style="width:100% ">
    <tr>
        <td>Location</td>
        <td>Address</td>
        <td>X Cord</td>
        <td>Y Cord</td>
        <td>Date From</td>
        <td>Date To</td>
        <td>Category</td>
        <td>Delete</td>
        <td>Update</td>
    </tr>
    {% for location in loaction_list %}
    <tr>
        <td>{{ location.locationCache.locationName }}</td>
        <td>{{ location.locationCache.address }}</td>
        <td>{{ location.locationCache.xCord }}</td>
        <td>{{ location.locationCache.yCord }}</td>
        <td>{{ location.dateFrom }}</td>
        <td>{{ location.dateTo }}</td>
        <td>{{ location.category }}</td>
        <td><a href="{% url 'location-delete' location.pk %}">Delete</a></td>
        <td><a href="{% url 'location-update' location.pk %}">Update</a></td>
    </tr>
    {% endfor %}
</table>

<div style="display: flex; flex-direction: column">
    <a href="{% url 'location-create' case.caseNumber %}">New Location</a>
    <a href="{% url 'case-all' %}">Back to Caes List</a>
</div>

HotZone/templates/case_create_form.html
<h1> Create New Case Record </h1>

<form method="post" id="caseCreateForm">
    {% csrf_token %}
    <p>
        <label>Case Number: </label>
        <input type="text" name="caseNumber" >
    </p>
    <p>
        <label>Date Confirmed: </label>
        <input type="date" name="dateConfirmed" >
    </p>
    <p>
        <label>Local or Import: </label>
        <select form="caseCreateForm" name="localOrImported" >
            <option value="Loacl">Local</option>
            <option value="Import">Import</option>
        </select>
    </p>
    <p>
        <label>Patient Name: </label>
        <input type="text" name="patientName" >
    </p>
    <p>
        <label>Id Number: </label>
        <input type="text" name="idNumber" >
    </p>
    <p>
        <label>Date Of Birth: </label>
        <input type="date" name="dateOfBirth" >
    </p>
    <p>
        <label>Virus: </label>
        <select form="caseCreateForm" name="virus" >
            <option value="SARS-CoV-2">SARS-CoV-2</option>
            <option value="GGGGGG">GGGGGG</option>
        </select>
    </p>
    <input type="submit" value="Create">
</form>

HotZone/templates/case_list.html
<h1>Showing all case</h1>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    jQuery(document).on("click", "tr > td", function () {
        var $this = jQuery(this);

        // ignore clicks on last column
        if ($this.is(":last-child")) return;

        // unhighlight currently selected row
        jQuery(".highlight").removeClass("highlight");

        // change the highlight of the row        
        $this.parent().addClass("highlight");
    });

    function call_counter(url) {
        window.open(url);
    }
</script>

<style>
    table,
    th,
    td {
        border: 1px solid rgb(235, 59, 59);
        border-collapse: collapse;
    }

    .highlight {
        background-color: #fa9da9;
    }
</style>

<table style="width:100% ">
    <tr>
        <th>Case Number</th>
        <th>Date Confirmed</th>
        <th>Local or Imported</th>
        <th>Patient Name</th>
        <th>ID Number</th>
        <th>Date of Birth</th>
        <th>Virus Name</th>
        <th>Disease</th>
        <th>Max Infectious Period</th>
    </tr>
    {% for case in case_list %}
    <tr>
        <td>
            <a href="{% url 'case' case.caseNumber %}">
                {{ case.caseNumber }}
            </a>
        </td>
        <td>{{ case.dateConfirmed }}</td>
        <td>{{ case.localOrImported }}</td>
        <td>{{ case.patientName }}</td>
        <td>{{ case.idNumber }}</td>
        <td>{{ case.dateOfBirth }}</td>
        <td>{{ case.virusName }}</td>
        <td>{{ case.disease }}</td>
        <td>{{ case.maxInfectiousPeriod }}</td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'case-create' %}">
    Add Case
</a>

HotZone/templates/case_update_form.html
<h1> Update Case Record {{ Case.caseNumber }} </h1>

<form method="post" id="caseCreateForm">
    {% csrf_token %}
    <p>
        <label>Case Number: </label>
        <input type="text" name="caseNumber" value="{{ Case.caseNumber }}">
    </p>
    <p>
        <label>Date Confirmed: </label>
        <input type="date" name="dateConfirmed" value="{{ dateConfirmed }}">
    </p>
    <p>
        <label>Local or Import: </label>
        <select form="caseCreateForm" name="localOrImported" value="{{ Case.localOrImported }}">
            <option value="Loacl">Local</option>
            <option value="Import">Import</option>
        </select>
    </p>
    <p>
        <label>Patient Name: </label>
        <input type="text" name="patientName" value="{{ Case.patientName }}">
    </p>
    <p>
        <label>Id Number: </label>
        <input type="text" name="idNumber" value="{{ Case.idNumber }}">
    </p>
    <p>
        <label>Date Of Birth: </label>
        <input type="date" name="dateOfBirth" value="{{ dateOfBirth }}">
    </p>
    <p>
        <label>Virus: </label>
        <select form="caseCreateForm" name="virus" value="{{ Case.virus }}">
            <option value="SARS-CoV-2">SARS-CoV-2</option>
            <option value="GGGGGG">GGGGGG</option>
        </select>
    </p>
    <input type="submit" value="Update">
</form>

HotZone/templates/customer_list.html
<h1>Showing all customers</h1>
<ul>
    {% for customer in customer_list %}
    <li>
        <a href="{% url 'customer-orders' customer.pk %}">
            {{ customer.name }}
        </a>
        ({{ customer.order_set.all | length }})
    </li>
    {% empty %}
    <li>No customer yet.</li>
    {% endfor %}
</ul>

HotZone/templates/loaction_cache_already_exist.html
<h1> Create New Location Data </h1>

<p>The location you searched has already exist</p>

<a href="{% url 'case-all' %}">Back to Caes List</a>

HotZone/templates/location_cache_create_confirm.html
<h1> Create New Location Data </h1>

<p>You are about to create new location Data</p>
<p> </p>
<p>Name: {{ jsonData.nameEN }}</p>
<p>Address: {{ jsonData.addressEN }}</p>
<p>X Cord: {{ jsonData.x }}</p>
<p>Y Cord: {{ jsonData.y }}</p>
<p> </p>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="confirm">
    <input type="hidden" name="jsonData" value="{{ jsonData }}">

    <input type="submit" value="Confirm">
</form>

<a href="{% url 'case-all' %}">Back to Caes List</a>

HotZone/templates/location_cache_create_form.html
<h1> Create New Location Data </h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="search">
    <p>
        <label>Search Location: </label>
        <input type="text" name="locationName">
    </p>
    <input type="submit" value="Search">
</form>

HotZone/templates/location_cache_create_select.html
<h1> Create New Location Data </h1>

{% if exist %}
<p>The location you searched has already exist</p>

{% elif jsonData_list|length > 0 %}

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="select">

    <p>
        <label>location avaliable: </label>
        <select name="jsonData">
            {% for jsonData in jsonData_list %}
            <option value="{{ jsonData }}">
                {{ jsonData.addressEN }}
            </option>
            {% endfor %}
        </select>
    </p>

    <input type="submit" value="Select">
</form>

{% else %}
<p>No matching result</p>

{% endif %}

<a href="{% url 'case-all' %}">Back to Caes List</a>

HotZone/templates/location_create_form.html
<h1> Create New Visit Record for {{ caseNumber }} </h1>

<form method="post">
    {% csrf_token %}
    <input style="display: none;" name="caseNumber" value="{{ caseNumber_pk }}">
    <p>
        <label>Location: </label>
        <select name="locationCache">
            {% for locationCache in locationCache_list %}
            <option value="{{ locationCache.pk }}">
                {{ locationCache.locationName }}
            </option>
            {% endfor %}
        </select>
        <a href="/recordPage/location_cache_create/create/{{ caseNumber }}">New Location Data</a>
    </p>
    <p>
        <label>Date From: </label>
        <input type="date" name="dateFrom" >
    </p>
    <p>
        <label>Date To: </label>
        <input type="date" name="dateTo" >
    </p>
    <p>
        <label>category: </label>
        <select type="text" name="category" value="{{ Location.category }}">
            <option value="Residence">Residence</option>
            <option value="Workplace">Workplace</option>
            <option value="Visit">Visit</option>
        </select>
    </p>
    <p>
        <input type="submit" value="Create">
    </p>
    <p>
        <a href="/recordPage/case/{{ caseNumber }}">Back to Caes</a>
    </p>
</form>

HotZone/templates/location_update_form.html
<h1> Update Visit Record for {{ Location.case }}( {{ Location.locationCache.locationName }}) </h1>

<form method="post">
    {% csrf_token %}
    <input style="display: none;" name="case" value="{{ Location.case_id }}">
    <p>
        <label>Location: </label>
        <select name="locationCache">
            {% for locationCache in LocationCache_list %}
            <option value="{{ locationCache.pk }}">
                {{ locationCache.locationName }}
            </option>
            {% endfor %}
        </select>
        <a href="/recordPage/location_cache_create/update/{{ Location.pk }}">New Location Data</a>
    </p>
    <p>
        <label>Date From: </label>
        <input type="date" name="dateFrom" value="{{ dateFrom }}">
    </p>
    <p>
        <label>Date To: </label>
        <input type="date" name="dateTo" value="{{ dateTo }}">
    </p>
    <p>
        <label>category: </label>
        <select type="text" name="category" value="{{ Location.category }}">
            <option value="Residence">Residence</option>
            <option value="Workplace">Workplace</option>
            <option value="Visit">Visit</option>
        </select>
    </p>
    <p>
        <input type="submit" value="Update">
    </p>
    <p>
        <a href="/recordPage/case/{{ Location.case }}">Back to Caes</a>
    </p>
</form>

HotZone/templates/order_list.html
<h1>Showing all orders by {{ customer.name }}</h1>

<ul>

    {% for order in order_list %}
    <li>[{{ order.status }}] {{ order.time }}
        <ul>
            {% for item in order.items.all %}
            <li>{{ item.name }} ({{ item.price }})</li>
            {% endfor %}
        </ul>
    </li>
    {% empty %}
    <li>No order yet.</li>
    {% endfor %}

</ul>